# Sponsor AwareXone — https://github.com/sponsors/awarexone
# Powered by AwareXone.com — https://awarexone.com

github: [awarexone]
custom:
  - https://awarexone.com
  - https://www.buymeacoffee.com/shuvonsec

